### PR TITLE
Fix pymatgen related imports

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by utf** [comment]
Thanks very much for this.

As robocrys depends on matminer, I need to wait until matminer supports the latest version of pymatgen. My PR updating matminer has been merged but I'm still waiting for a new version to be released: https://github.com/hackingmaterials/matminer/pull/603

**Comment by jan-janssen** [comment]
Btw. I created a conda-forge package for robocrys https://anaconda.org/conda-forge/robocrys and the matminer package on conda-forge is patched as well, just in case that helps. In addition if you are interested in joining me with maintaining the conda-forge package, I can add you as a maintainer.

**Comment by utf** [comment]
I noticed that earlier. Thanks for that.

I don't have much experience releasing conda packages but if is not too difficult then perhaps it could be added as part of the release pipeline: https://github.com/hackingmaterials/robocrystallographer/blob/main/.github/workflows/release.yml

**Comment by jan-janssen** [comment]
That is not necessary, conda is using the pip package and the pull request is merged automatically unless the dependencies changed. Only in case something goes wrong - like the recent change of pymatgen - then it is possible to patch the packages to release a new build on conda-forge before the new package is released.

**Comment by jan-janssen** [comment]
This is the repository for managing the conda-forge package https://github.com/conda-forge/robocrys-feedstock/ in there it is primary the meta.yaml file https://github.com/conda-forge/robocrys-feedstock/blob/master/recipe/meta.yaml which controls the build process.

**Comment by utf** [comment]
This should now be resolved.

**Pull request closed without merging**
